// Generated by github.com/davyxu/tabtoy
// Version: 2.8.7
// DO NOT EDIT!!
using System.Collections.Generic;

namespace table
{
	
	

	// Defined in table: Config
	
	public partial class Config
	{
	
		public tabtoy.Logger TableLogger = new tabtoy.Logger();
	
		
		/// <summary> 
		/// Item
		/// </summary>
		public List<ItemDefine> Item = new List<ItemDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, ItemDefine> _ItemByID = new Dictionary<int, ItemDefine>();
        public ItemDefine GetItemByID(int ID, ItemDefine def = default(ItemDefine))
        {
            ItemDefine ret;
            if ( _ItemByID.TryGetValue( ID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(ItemDefine) )
			{
				TableLogger.ErrorLine("GetItemByID failed, ID: {0}", ID);
			}

            return def;
        }
		
	
		#endregion
		#region Deserialize code
		
		static tabtoy.DeserializeHandler<Config> _ConfigDeserializeHandler;
		static tabtoy.DeserializeHandler<Config> ConfigDeserializeHandler
		{
			get
			{
				if (_ConfigDeserializeHandler == null )
				{
					_ConfigDeserializeHandler = new tabtoy.DeserializeHandler<Config>(Deserialize);
				}

				return _ConfigDeserializeHandler;
			}
		}
		public static void Deserialize( Config ins, tabtoy.DataReader reader )
		{
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0xa0000:
                	{
						ins.Item.Add( reader.ReadStruct<ItemDefine>(ItemDefineDeserializeHandler) );
                	}
                	break; 
                }
             }

			
			// Build Item Index
			for( int i = 0;i< ins.Item.Count;i++)
			{
				var element = ins.Item[i];
				
				ins._ItemByID.Add(element.ID, element);
				
			}
			
		}
		static tabtoy.DeserializeHandler<ItemDefine> _ItemDefineDeserializeHandler;
		static tabtoy.DeserializeHandler<ItemDefine> ItemDefineDeserializeHandler
		{
			get
			{
				if (_ItemDefineDeserializeHandler == null )
				{
					_ItemDefineDeserializeHandler = new tabtoy.DeserializeHandler<ItemDefine>(Deserialize);
				}

				return _ItemDefineDeserializeHandler;
			}
		}
		public static void Deserialize( ItemDefine ins, tabtoy.DataReader reader )
		{
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x10000:
                	{
						ins.ID = reader.ReadInt32();
                	}
                	break; 
                	case 0x60001:
                	{
						ins.Name = reader.ReadString();
                	}
                	break; 
                	case 0x10002:
                	{
						ins.UpgradeCost = reader.ReadInt32();
                	}
                	break; 
                	case 0x10003:
                	{
						ins.GenPetID = reader.ReadInt32();
                	}
                	break; 
                }
             }

			
		}
		#endregion
	

	} 

	// Defined in table: Item
	
	public partial class ItemDefine
	{
	
		
		/// <summary> 
		/// 唯一ID
		/// </summary>
		public int ID = 0; 
		
		/// <summary> 
		/// 名称
		/// </summary>
		public string Name = ""; 
		
		/// <summary> 
		/// 进阶消耗
		/// </summary>
		public int UpgradeCost = 0; 
		
		/// <summary> 
		/// 使用后生成的宠物
		/// </summary>
		public int GenPetID = 0; 
	
	

	} 

}
